services:
  postgres:
    image: 'postgres:17-alpine3.22'
    container_name: recipes-db
    environment:
      - 'POSTGRES_DB=recipes'
      - 'POSTGRES_USER=user1'
      - 'POSTGRES_PASSWORD=pass1234'
    ports:
      - '5566:5432'
    volumes:
      - ./exampleDB:/var/lib/postgresql/data
    restart: always